### ISSUE TITLE
opening '﻿'__nanoversion__.txt'' in setup.py

### ISSUE THREAD

**Issue by matk86** [atztogo/phonopy#18] opened 2016-04-26 16:11 UTC
Its a very minor issue.
'pip install phonopy' fails because the version on pypi(1.10.4.59) tries to open the aforementioned file in setup.py. I noticed that the version on github doesnt have that problem. It would be nice to have a pip installable version so that packages that use phonopy can add it as a requirement in their setup.py files..

**Comment by atztogo** [comment] 2016-04-28 00:03
Thank you for letting me know it. Phonopy on pypi is now under the situation of trial and error of automated deployment. We will see and fix it.

**Comment by jochym** [comment] 2016-04-29 11:38
I'll fix it next weak. (Wednesday probably) Sorry! 
It is a side-effect of trying to have both conda and pip packages generated from the same source and automatically.

**Comment by matk86** [comment] 2016-04-29 14:32
Thanks. Looking forward to it.

**Comment by matk86** [comment] 2016-05-11 18:19
any updates?

**Comment by jochym** [comment] 2016-05-11 20:41
I have just fixed the same issue for spglib but lost my Internet right now
. i will fix phonopy tomorrow.

P.

śr., 11 maj 2016, 20:19 użytkownik Kiran Mathew <notifications@github.com>
napisał:

**Comment by jochym** [comment] 2016-05-12 13:35
I believe the issue is fixed now and hopefully for the future. The automatic ci/deploynment has been improved and should not allow for breakage like this. I think the issue may be closed now.

**Closed** 2016-05-12 13:46 UTC

**Comment by matk86** [comment] 2016-05-12 13:49
Thanks

**Comment by matk86** [comment] 2016-05-12 16:29
any reason why the pypi release(1.10.4.46) is not the latest one, 1.10.8?

**Comment by jochym** [comment] 2016-05-12 21:03
Look again ;) Now it is. You just "caught me in the act" of preparing releases .

**Comment by matk86** [comment] 2016-05-12 21:06
great 👍 
thanks
