### ISSUE TITLE
setup.py requires numpy to work

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#53] opened 2017-09-07 17:44 UTC
The `import numpy` at the beginning of `setup.py` prevents things like `pip install phonopy` from working on a machine that doesn't have `numpy` installed.

I'm not sure how to best fix this myself, but it looks like there's an example of how to get around this in [scipy's setup.py](https://github.com/scipy/scipy/blob/master/setup.py#L397-L412)

**Comment by atztogo** [comment] 2017-09-07 18:05
I will think. Thanks.

**Comment by atztogo** [comment] 2018-04-22 08:25
I'm sorry leaving this issue unsolved. `numpy.get_include()` is needed to pass this information to `setup`. I couldn't see how to solve it reading your scipy link. Maybe just showing some notification that numpy installation is necessary is a simple solution.

**Comment by flokno** [comment] 2019-07-19 15:20
I ran into this as well. There is a way with `pyproject.toml` using `[build-system]`:
```
[build-system]
requires = ["setuptools", "numpy"]
```
That makes sure `numpy` is there when `numpy` is also a dependency of the project.

The problem is that currently `phonopy` doesn't handle it's own dependencies, which are only 4. I have a project with ~20 dependencies, one of which `phonopy`, and it doesn't install into a fresh virtual environment only because of `phonopy`.

It's not a huge issue, but it could be solved and would allow you to be able to be installed via `pip` to fresh systems.

**Comment by atztogo** [comment] 2019-07-20 07:43
I am not good at these stuff, so I need your help, if we can fix it. Do you mean your problem will be fixed by putting `pyrpoject.toml`? Or can you give PR?

**Comment by flokno** [comment] 2019-07-26 08:50
I tested locally and `pip install phonopy` worked fine after including the `pyproject.toml` file, see PR.

**Comment by atztogo** [comment] 2019-07-26 10:49
Thanks. I'm going to merge it. I close this issue. We will reopen when we will find any issue on it in the future.

**Closed by atztogo** 2019-07-26 10:49 UTC
